// Module augmentation that makes every `t("…")` call type-checked
// against the actual JSON catalogues. This is the same outcome the
// spec describes (`web/src/i18n/resources.d.ts` generated by
// `i18next-resources-for-ts`), implemented as hand-written
// augmentation instead. Module augmentation is the idiomatic
// approach in i18next ≥ 21 and removes the need for a codegen step
// (which, in this project, is incompatible with Vite's
// `"type": "module"` package layout).
//
// Editing rules:
//   * The Resources interface MUST list every namespace declared in
//     the `ns:` array of `index.ts`. Otherwise the namespace would
//     compile fine but `t("ns:key")` would resolve to `string`
//     (un-checked).
//   * Always source the value types from `typeof <pl json>` (the
//     fallback locale). All other locales MUST mirror the same keys
//     — a missing key in `en/` is then a type error, not a runtime
//     "key returned untranslated" surprise.

import "i18next";

import type plCommon from "./locales/pl/common.json";
import type plAuth from "./locales/pl/auth.json";
import type plErrors from "./locales/pl/errors.json";
import type plRole from "./locales/pl/role.json";
import type plHome from "./locales/pl/home.json";
import type plLayout from "./locales/pl/layout.json";
import type plInterlocking from "./locales/pl/interlocking.json";

declare module "i18next" {
  interface CustomTypeOptions {
    defaultNS: "common";
    resources: {
      common: typeof plCommon;
      auth: typeof plAuth;
      errors: typeof plErrors;
      role: typeof plRole;
      home: typeof plHome;
      layout: typeof plLayout;
      interlocking: typeof plInterlocking;
    };
    // returnNull is false in index.ts; mirror that here so the t()
    // return type is `string` (not `string | null`).
    returnNull: false;
  }
}
