package supervisord

import (
	"bytes"
	"fmt"
	"path/filepath"
	"text/template"
)

const (
	// DefaultTelemetryConfigPath is the Alloy config file on hub images.
	DefaultTelemetryConfigPath = "/data/etc/alloy.conf"
	// DefaultAlloyStoragePath is Alloy's on-disk state directory.
	DefaultAlloyStoragePath = "/data/alloy"
	// DefaultOTLPEndpoint is the loopback gRPC receiver dcc-bus exports to.
	DefaultOTLPEndpoint = "127.0.0.1:4317"
)

const bigfredAlloyOTELTemplateGrafanaCloud = `// Generated by loco-server — BigFred dcc-bus OTLP/gRPC receiver.

otelcol.receiver.otlp "bigfred" {
	grpc {
		endpoint = "{{ .OTLPEndpoint }}"
	}

	output {
		metrics = [otelcol.processor.batch.bigfred.input]
	}
}

otelcol.processor.batch "bigfred" {
	output {
		metrics = [otelcol.exporter.otlphttp.bigfred.input]
	}
}

otelcol.exporter.otlphttp "bigfred" {
	client {
		endpoint = sys.env("GRAFANA_CLOUD_OTLP_ENDPOINT")
		auth     = otelcol.auth.basic.bigfred.handler
	}
}

otelcol.auth.basic "bigfred" {
	username = sys.env("GRAFANA_CLOUD_INSTANCE_ID")
	password = sys.env("GRAFANA_CLOUD_API_KEY")
}
`

var bigfredAlloyOTELTmplGrafanaCloud = template.Must(template.New("bigfred-otel-grafana-cloud").Parse(bigfredAlloyOTELTemplateGrafanaCloud))

// TelemetryConfig controls the managed Grafana Alloy process.
type TelemetryConfig struct {
	Enable      bool
	AlloyBin    string
	ConfigPath  string
	StoragePath string
	// OTLPEndpoint is written into the generated Alloy receiver block.
	OTLPEndpoint string
}

type alloyOTELTemplateData struct {
	OTLPEndpoint string
}

// AlloyRunConfigPath returns the single path passed to `alloy run`.
func AlloyRunConfigPath(cfg TelemetryConfig) string {
	return resolveTelemetryConfigPath(cfg)
}

// BigFredAlloyGeneratedPath returns the path the BigFred Alloy config is
// written to before Alloy starts. It is always the resolved ConfigPath.
func BigFredAlloyGeneratedPath(cfg TelemetryConfig) string {
	return resolveTelemetryConfigPath(cfg)
}

// PrepareAlloyTelemetry renders the BigFred Grafana Cloud OTLP Alloy config
// from bigfredAlloyOTELTemplateGrafanaCloud and overwrites it at ConfigPath
// before Alloy starts.
func PrepareAlloyTelemetry(cfg TelemetryConfig) error {
	content, err := renderBigFredAlloyOTEL(cfg)
	if err != nil {
		return err
	}
	configPath := resolveTelemetryConfigPath(cfg)
	if err := EnsureDir(filepath.Dir(configPath)); err != nil {
		return err
	}
	return WriteConfigAtomically(configPath, content)
}

func renderBigFredAlloyOTEL(cfg TelemetryConfig) ([]byte, error) {
	endpoint := cfg.OTLPEndpoint
	if endpoint == "" {
		endpoint = DefaultOTLPEndpoint
	}
	var buf bytes.Buffer
	if err := bigfredAlloyOTELTmplGrafanaCloud.Execute(&buf, alloyOTELTemplateData{OTLPEndpoint: endpoint}); err != nil {
		return nil, fmt.Errorf("render alloy otel template: %w", err)
	}
	return buf.Bytes(), nil
}

func resolveTelemetryConfigPath(cfg TelemetryConfig) string {
	if cfg.ConfigPath != "" {
		return cfg.ConfigPath
	}
	return DefaultTelemetryConfigPath
}
