package supervisord

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const (
	// DefaultTelemetryConfigPath is the Alloy config file on hub images.
	DefaultTelemetryConfigPath = "/data/etc/alloy.conf"
	// DefaultAlloyStoragePath is Alloy's on-disk state directory.
	DefaultAlloyStoragePath = "/data/alloy"
	// DefaultOTLPEndpoint is the loopback gRPC receiver dcc-bus exports to.
	DefaultOTLPEndpoint   = "127.0.0.1:4317"
	bigfredOTELFilename   = "bigfred-otel.alloy"
	operatorAlloyLinkName = "operator.alloy"
)

const bigfredAlloyOTELTemplateLocal = `// Generated by loco-server — BigFred dcc-bus OTLP/gRPC receiver (local only).

otelcol.receiver.otlp "bigfred" {
	grpc {
		endpoint = "{{ .OTLPEndpoint }}"
	}
}
`

const bigfredAlloyOTELTemplateGrafanaCloud = `// Generated by loco-server — BigFred dcc-bus OTLP/gRPC receiver.

otelcol.receiver.otlp "bigfred" {
	grpc {
		endpoint = "{{ .OTLPEndpoint }}"
	}

	output {
		metrics = [otelcol.processor.batch.bigfred.input]
	}
}

otelcol.processor.batch "bigfred" {
	output {
		metrics = [otelcol.exporter.otlphttp.bigfred.input]
	}
}

otelcol.exporter.otlphttp "bigfred" {
	client {
		endpoint = sys.env("GRAFANA_CLOUD_OTLP_ENDPOINT")
		auth     = otelcol.auth.basic.bigfred.handler
	}
}

otelcol.auth.basic "bigfred" {
	username = sys.env("GRAFANA_CLOUD_INSTANCE_ID")
	password = sys.env("GRAFANA_CLOUD_API_KEY")
}
`

var (
	bigfredAlloyOTELTmplLocal        = template.Must(template.New("bigfred-otel-local").Parse(bigfredAlloyOTELTemplateLocal))
	bigfredAlloyOTELTmplGrafanaCloud = template.Must(template.New("bigfred-otel-grafana-cloud").Parse(bigfredAlloyOTELTemplateGrafanaCloud))
)

// TelemetryConfig controls the managed Grafana Alloy process.
type TelemetryConfig struct {
	Enable      bool
	AlloyBin    string
	ConfigPath  string
	StoragePath string
	// OTLPEndpoint is written into the generated Alloy receiver block.
	OTLPEndpoint string
	// SupervisordConfigDir is where the generated Alloy runtime directory
	// is created when --telemetry-config points at a single file.
	SupervisordConfigDir string
}

type alloyOTELTemplateData struct {
	OTLPEndpoint string
}

// AlloyRunConfigPath returns the single path passed to `alloy run`.
func AlloyRunConfigPath(cfg TelemetryConfig) string {
	return alloyRunConfigPath(cfg)
}

// BigFredAlloyGeneratedPath returns the path of the templated BigFred OTLP
// receiver block after PrepareAlloyTelemetry runs.
func BigFredAlloyGeneratedPath(configDir string, cfg TelemetryConfig) string {
	return bigfredOTELConfigPath(configDir, cfg)
}

// PrepareAlloyTelemetry renders the BigFred OTLP receiver Alloy config into
// the supervisord config directory (or the operator config directory when it
// is already a directory path).
func PrepareAlloyTelemetry(configDir string, cfg TelemetryConfig) error {
	if configDir == "" {
		return fmt.Errorf("supervisord config dir required for alloy telemetry")
	}
	content, err := renderBigFredAlloyOTEL(cfg)
	if err != nil {
		return err
	}

	configPath := cfg.ConfigPath
	if configPath == "" {
		configPath = DefaultTelemetryConfigPath
	}
	info, err := os.Stat(configPath)
	if err == nil && info.IsDir() {
		return WriteConfigAtomically(filepath.Join(configPath, bigfredOTELFilename), content)
	}

	runtimeDir := alloyRuntimeDir(configDir)
	if err := EnsureDir(runtimeDir); err != nil {
		return err
	}
	if err := WriteConfigAtomically(filepath.Join(runtimeDir, bigfredOTELFilename), content); err != nil {
		return err
	}
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("stat alloy config %s: %w", configPath, err)
	}
	return linkAlloyOperatorConfig(runtimeDir, configPath)
}

func grafanaCloudOTELConfigured() bool {
	for _, key := range []string{
		"GRAFANA_CLOUD_OTLP_ENDPOINT",
		"GRAFANA_CLOUD_INSTANCE_ID",
		"GRAFANA_CLOUD_API_KEY",
	} {
		if strings.TrimSpace(os.Getenv(key)) == "" {
			return false
		}
	}
	return true
}

func renderBigFredAlloyOTEL(cfg TelemetryConfig) ([]byte, error) {
	endpoint := cfg.OTLPEndpoint
	if endpoint == "" {
		endpoint = DefaultOTLPEndpoint
	}
	data := alloyOTELTemplateData{OTLPEndpoint: endpoint}
	var buf bytes.Buffer
	tmpl := bigfredAlloyOTELTmplLocal
	if grafanaCloudOTELConfigured() {
		tmpl = bigfredAlloyOTELTmplGrafanaCloud
	}
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("render alloy otel template: %w", err)
	}
	return buf.Bytes(), nil
}

func alloyRuntimeDir(configDir string) string {
	return filepath.Join(configDir, "alloy")
}

func alloyRunConfigPath(cfg TelemetryConfig) string {
	configPath := cfg.ConfigPath
	if configPath == "" {
		configPath = DefaultTelemetryConfigPath
	}
	if !cfg.Enable {
		return configPath
	}
	if info, err := os.Stat(configPath); err == nil && info.IsDir() {
		return configPath
	}
	if cfg.SupervisordConfigDir == "" {
		return configPath
	}
	return alloyRuntimeDir(cfg.SupervisordConfigDir)
}

func bigfredOTELConfigPath(configDir string, cfg TelemetryConfig) string {
	configPath := cfg.ConfigPath
	if configPath == "" {
		configPath = DefaultTelemetryConfigPath
	}
	if info, err := os.Stat(configPath); err == nil && info.IsDir() {
		return filepath.Join(configPath, bigfredOTELFilename)
	}
	return filepath.Join(alloyRuntimeDir(configDir), bigfredOTELFilename)
}

func linkAlloyOperatorConfig(runtimeDir, configFile string) error {
	abs, err := filepath.Abs(configFile)
	if err != nil {
		return fmt.Errorf("abs alloy config path: %w", err)
	}
	linkPath := filepath.Join(runtimeDir, operatorAlloyLinkName)
	if err := os.Remove(linkPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("remove stale alloy operator link: %w", err)
	}
	if err := os.Symlink(abs, linkPath); err != nil {
		return fmt.Errorf("link alloy operator config: %w", err)
	}
	return nil
}
